sonar.projectKey=neerajvijeth_HPE-CPP3-TEAM-4
sonar.organization=neerajvijeth
sonar.projectName=SecureVault DevSecOps
sonar.sources=app
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
