"""
SecDebt Report Parsers
======================
Parses the EXISTING report files generated by each GitHub Actions workflow:

  bandit     → bandit-report.txt      (text output from: bandit -r app/ -ll)
  trivy      → trivy-results.txt      (table format from trivy-action)
  pylint     → pylint-report.txt      (text output from: pylint app/)
  owasp      → odc-reports/dependency-check-report.json
  sonar      → sonar-issues.json      (fetched via SonarCloud API, optional)

Each parser returns a list of dicts with keys:
  tool, vuln_id, title, description, severity,
  reachability, file_path, line_number, raw_snippet
"""

import re
import json
import os
import logging
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Severity normalizer
# ---------------------------------------------------------------------------

def normalize_severity(raw: str) -> str:
    """Map any tool-specific severity string to CRITICAL/HIGH/MEDIUM/LOW/INFO."""
    mapping = {
        "critical": "CRITICAL",
        "high": "HIGH",
        "medium": "MEDIUM",
        "moderate": "MEDIUM",
        "low": "LOW",
        "warning": "LOW",
        "info": "INFO",
        "informational": "INFO",
        "note": "INFO",
        "negligible": "INFO",
        "unknown": "MEDIUM",
    }
    return mapping.get(str(raw).lower().strip(), "MEDIUM")


# ---------------------------------------------------------------------------
# Reachability heuristics
# ---------------------------------------------------------------------------

def estimate_reachability(tool: str, file_path: Optional[str], vuln_id: str) -> float:
    """
    Simple heuristic:
      - app/ code (Bandit/Pylint) → 1.0 (directly in running app)
      - OS image vulns (Trivy OS) → 0.3 (likely not exposed)
      - Library vulns (Trivy lib / OWASP) → 0.7 (dependency chain)
      - SonarQube code issues → 0.8
    """
    if file_path:
        fp = file_path.lower()
        if fp.startswith("app/") or "/app/" in fp:
            return 1.0
        if "test" in fp or "spec" in fp:
            return 0.2
    if tool == "trivy_os":
        return 0.3
    if tool in ("trivy_lib", "owasp"):
        return 0.7
    if tool == "sonar":
        return 0.8
    return 0.5


# ---------------------------------------------------------------------------
# Bandit parser  (bandit-report.txt)
# ---------------------------------------------------------------------------

def parse_bandit(report_path: str) -> list[dict]:
    """
    Bandit text output looks like:
    >> Issue: [B105:hardcoded_password_string] Possible hardcoded password ...
       Severity: Medium   Confidence: Medium
       CWE: CWE-259
       Location: app/routes/auth.py:42:8
       ...
    """
    findings = []
    if not os.path.exists(report_path):
        logger.warning("Bandit report not found: %s", report_path)
        return findings

    with open(report_path, "r", encoding="utf-8", errors="replace") as fh:
        content = fh.read()

    # Split on issue blocks
    blocks = re.split(r"(?=^>> Issue:)", content, flags=re.MULTILINE)
    for block in blocks:
        block = block.strip()
        if not block.startswith(">> Issue:"):
            continue

        # vuln_id + title
        m_issue = re.search(r"\[(\w+:[^\]]+)\]\s*(.+)", block)
        if not m_issue:
            continue
        vuln_id = m_issue.group(1).strip()
        title = m_issue.group(2).strip()

        # severity
        m_sev = re.search(r"Severity:\s*(\w+)", block, re.IGNORECASE)
        severity = normalize_severity(m_sev.group(1)) if m_sev else "MEDIUM"

        # location
        m_loc = re.search(r"Location:\s*(.+?):(\d+)", block)
        file_path = m_loc.group(1).strip() if m_loc else None
        line_number = int(m_loc.group(2)) if m_loc else None

        findings.append({
            "tool": "bandit",
            "vuln_id": vuln_id,
            "title": title,
            "description": f"Bandit static analysis: {vuln_id}",
            "severity": severity,
            "reachability": estimate_reachability("bandit", file_path, vuln_id),
            "file_path": file_path,
            "line_number": line_number,
            "raw_snippet": block[:400],
        })

    logger.info("Bandit: parsed %d findings", len(findings))
    return findings


# ---------------------------------------------------------------------------
# Trivy parser  (trivy-results.txt)
# ---------------------------------------------------------------------------

def parse_trivy(report_path: str) -> list[dict]:
    """
    Trivy table output:
    ┌────────────────┬──────────────────┬──────────┬──────────────┬───────────────────┐
    │   Library      │  Vulnerability   │ Severity │ Installed    │ Fixed Version     │
    ├────────────────┼──────────────────┼──────────┼──────────────┼───────────────────┤
    │ cryptography   │ CVE-2023-49083   │ HIGH     │ 41.0.4       │ 41.0.6            │
    └────────────────┴──────────────────┴──────────┴──────────────┴───────────────────┘

    We use regex to grab CVE IDs and severity from the table rows.
    """
    findings = []
    if not os.path.exists(report_path):
        logger.warning("Trivy report not found: %s", report_path)
        return findings

    with open(report_path, "r", encoding="utf-8", errors="replace") as fh:
        lines = fh.readlines()

    # Detect if this is an OS section or library section
    current_section = "library"
    for line in lines:
        if re.search(r"OS Packages|debian|ubuntu|alpine", line, re.IGNORECASE):
            current_section = "os"
        if re.search(r"Python Packages|pip|library", line, re.IGNORECASE):
            current_section = "library"

        # Table data row with CVE
        m = re.search(
            r"│\s*(\S.*?)\s*│\s*(CVE-[\d-]+|GHSA-[\w-]+)\s*│\s*(\w+)\s*│",
            line,
        )
        if m:
            library = m.group(1).strip()
            cve = m.group(2).strip()
            severity = normalize_severity(m.group(3).strip())
            tool_key = f"trivy_{current_section}"
            findings.append({
                "tool": "trivy",
                "vuln_id": cve,
                "title": f"{cve} in {library}",
                "description": f"Trivy detected {cve} in {library} ({current_section} package)",
                "severity": severity,
                "reachability": estimate_reachability(tool_key, None, cve),
                "file_path": None,
                "line_number": None,
                "raw_snippet": line.strip()[:400],
            })

    logger.info("Trivy: parsed %d findings", len(findings))
    return findings


# ---------------------------------------------------------------------------
# Pylint parser  (pylint-report.txt)
# ---------------------------------------------------------------------------

def parse_pylint(report_path: str) -> list[dict]:
    """
    Pylint output line format:
      app/routes/auth.py:42:0: W0611: Unused import os (unused-import)
      app/models/user.py:10:4: C0301: Line too long (105/100) (line-too-long)

    We only surface W (warning) and E (error) codes to reduce noise.
    C (convention) and R (refactor) are included but rated INFO.
    """
    findings = []
    if not os.path.exists(report_path):
        logger.warning("Pylint report not found: %s", report_path)
        return findings

    # Map pylint message type to severity
    type_severity = {
        "E": "HIGH",    # Error
        "W": "MEDIUM",  # Warning
        "C": "INFO",    # Convention
        "R": "INFO",    # Refactor
        "I": "INFO",    # Informational
        "F": "HIGH",    # Fatal
    }

    pattern = re.compile(
        r"^(.+?):(\d+):\d+:\s+([EWCRI]\d+):\s+(.+?)\s+\((\S+)\)"
    )
    with open(report_path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = pattern.match(line.strip())
            if not m:
                continue
            file_path = m.group(1).strip()
            line_number = int(m.group(2))
            code = m.group(3).strip()
            message = m.group(4).strip()
            symbol = m.group(5).strip()
            msg_type = code[0]
            severity = type_severity.get(msg_type, "INFO")

            findings.append({
                "tool": "pylint",
                "vuln_id": code,
                "title": f"{code}: {symbol}",
                "description": message,
                "severity": severity,
                "reachability": estimate_reachability("pylint", file_path, code),
                "file_path": file_path,
                "line_number": line_number,
                "raw_snippet": line.strip()[:400],
            })

    logger.info("Pylint: parsed %d findings", len(findings))
    return findings


# ---------------------------------------------------------------------------
# OWASP Dependency-Check parser  (dependency-check-report.json)
# ---------------------------------------------------------------------------

def parse_owasp(report_path: str) -> list[dict]:
    """
    OWASP DC JSON format:
    {
      "dependencies": [
        {
          "fileName": "cryptography-41.0.4.dist-info/METADATA",
          "vulnerabilities": [
            {
              "name": "CVE-2023-49083",
              "severity": "HIGH",
              "description": "...",
              "cvssv3": { "baseScore": 7.5 }
            }
          ]
        }
      ]
    }
    """
    findings = []
    if not os.path.exists(report_path):
        logger.warning("OWASP DC report not found: %s", report_path)
        return findings

    try:
        with open(report_path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, IOError) as e:
        logger.error("Failed to parse OWASP report: %s", e)
        return findings

    for dep in data.get("dependencies", []):
        dep_name = dep.get("fileName", dep.get("filePath", "unknown"))
        for vuln in dep.get("vulnerabilities", []):
            cve = vuln.get("name", "UNKNOWN")
            severity = normalize_severity(vuln.get("severity", "MEDIUM"))
            desc = vuln.get("description", "")[:500]
            findings.append({
                "tool": "owasp",
                "vuln_id": cve,
                "title": f"{cve} in {dep_name}",
                "description": desc,
                "severity": severity,
                "reachability": estimate_reachability("owasp", None, cve),
                "file_path": dep_name,
                "line_number": None,
                "raw_snippet": f"{cve} | {severity} | {dep_name}"[:400],
            })

    logger.info("OWASP: parsed %d findings", len(findings))
    return findings


# ---------------------------------------------------------------------------
# SonarQube / SonarCloud parser  (sonar-issues.json — optional)
# ---------------------------------------------------------------------------

def parse_sonar(report_path: str) -> list[dict]:
    """
    Optional: if you export SonarCloud issues via API and save as sonar-issues.json.
    Expected format (SonarCloud REST API /api/issues/search response):
    {
      "issues": [
        {
          "key": "AXxxx",
          "rule": "python:S1481",
          "severity": "MAJOR",
          "message": "Remove this unused \"os\" import.",
          "component": "org:repo:app/routes/auth.py",
          "line": 1,
          "type": "CODE_SMELL"
        }
      ]
    }
    """
    findings = []
    if not os.path.exists(report_path):
        logger.info("SonarQube report not found (optional): %s", report_path)
        return findings

    try:
        with open(report_path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, IOError) as e:
        logger.error("Failed to parse SonarQube report: %s", e)
        return findings

    sonar_sev_map = {
        "BLOCKER": "CRITICAL",
        "CRITICAL": "HIGH",
        "MAJOR": "MEDIUM",
        "MINOR": "LOW",
        "INFO": "INFO",
    }

    for issue in data.get("issues", []):
        rule = issue.get("rule", "UNKNOWN")
        severity = sonar_sev_map.get(issue.get("severity", "MAJOR"), "MEDIUM")
        message = issue.get("message", "")
        component = issue.get("component", "")
        # component like "org:repo:app/routes/auth.py" — extract path after last colon
        file_path = component.split(":")[-1] if ":" in component else component
        line_number = issue.get("line")

        findings.append({
            "tool": "sonar",
            "vuln_id": rule,
            "title": f"{rule}: {message[:80]}",
            "description": message,
            "severity": severity,
            "reachability": estimate_reachability("sonar", file_path, rule),
            "file_path": file_path,
            "line_number": line_number,
            "raw_snippet": f"{rule} | {severity} | {file_path}:{line_number}"[:400],
        })

    logger.info("SonarQube: parsed %d findings", len(findings))
    return findings
